e_vitrine_website:
    resource: "@EVitrineWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

e_vitrine_security_login:
    path:     /login
    defaults: { _controller: EVitrineDashboardBundle:Security:login }
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
e_vitrine_dashboard:
    resource: "@EVitrineDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

